// Site content data - edit via admin.html
const SITE_DATA = {
  logoText: "DSM-Firmenich",
  logoSrc: "",
  headerTagline: "우리는 삶에 진보를 가져옵니다",
  nav1: "사업부문", nav2: "회사소개", nav3: "채용", nav4: "투자자", nav5: "지속가능성", nav6: "뉴스",
  heroEyebrow: "2025 통합 연간 보고서",
  heroTitle: "우리는 삶에\n진보를 가져옵니다",
  heroDesc: "영양, 건강, 뷰티 분야의 글로벌 혁신 기업",
  heroCta: "자세히 보기",
  stat1Num: "€120억+", stat1Label: "통합 매출",
  stat2Num: "~30,000명", stat2Label: "글로벌 임직원",
  stat3Num: "150년+", stat3Label: "혁신의 역사",
  stat4Num: "2,000명+", stat4Label: "과학자 & 연구진",
  bizTitle: "우리의 사업 부문",
  bizSub: "글로벌 리더십으로 다양한 산업을 선도합니다",
  biz1Name: "향수 & 뷰티",
  biz1Desc: "세계 최고의 향수 및 화장품 성분을 개발하여 소비자에게 특별한 경험을 제공합니다.",
  biz2Name: "맛 & 질감 & 건강",
  biz2Desc: "혁신적인 맛과 질감 솔루션으로 식품 및 음료 산업의 미래를 만들어갑니다.",
  biz3Name: "건강 영양 & 케어",
  biz3Desc: "과학 기반의 영양 솔루션으로 전 세계 사람들의 건강과 웰빙을 증진시킵니다.",
  biz4Name: "동물 영양 & 건강",
  biz4Desc: "동물의 건강과 성능을 최적화하는 종합적인 영양 솔루션을 제공합니다.",
  sustainEyebrow: "지속가능성",
  sustainTitle: "지구와 사람을 위한\n책임있는 혁신",
  sustainDesc: "우리는 환경 보호, 책임있는 조달, 그리고 사회적 가치 창출을 통해 지속가능한 미래를 만들어 나갑니다.",
  sustainCta: "지속가능성 보기",
  sustainBadge1Title: "Net Zero 목표", sustainBadge1Desc: "2045년까지",
  sustainBadge2Title: "순환 경제", sustainBadge2Desc: "폐기물 제로 추구",
  sustainBadge3Title: "사회적 책임", sustainBadge3Desc: "100개국 이상에서 활동",
  innovEyebrow: "연구 & 혁신",
  innovTitle: "과학으로 세상을 바꿉니다",
  innovDesc: "2,000명 이상의 과학자들이 전 세계 R&D 시설에서 영양, 건강, 뷰티 분야의 글로벌 과제를 해결하기 위해 끊임없이 연구합니다.",
  innovCta: "연구 살펴보기",
  newsTitle: "최신 뉴스",
  news1Tag: "보도자료", news1Headline: "2025 통합 연간 보고서 발표",
  news1Excerpt: "dsm-firmenich이 2025년도 통합 연간 보고서를 공개하며 강력한 성장세와 지속가능성 목표 달성을 보고했습니다.",
  news1Date: "2026년 4월",
  news2Tag: "혁신", news2Headline: "차세대 향수 소재 개발 성공",
  news2Excerpt: "친환경 생물 기반 향수 소재 개발에 성공하여 지속가능한 뷰티 산업의 새로운 기준을 제시합니다.",
  news2Date: "2026년 3월",
  news3Tag: "지속가능성", news3Headline: "재생에너지 전환 50% 달성",
  news3Excerpt: "전 세계 생산 시설의 50% 이상을 재생에너지로 전환 완료하며 Net Zero 목표를 향한 중요한 이정표를 세웠습니다.",
  news3Date: "2026년 2월",
  cta1Title: "함께 성장할 인재를 찾습니다",
  cta1Desc: "글로벌 무대에서 당신의 가능성을 펼치세요",
  cta1Btn: "채용 공고 보기",
  cta2Title: "투자자 정보",
  cta2Desc: "재무 성과 및 투자자 관계 자료를 확인하세요",
  cta2Btn: "투자자 센터",
  footerLogoText: "DSM-Firmenich",
  footerSlogan: "우리는 삶에 진보를 가져옵니다",
  footerCopy: "© 2026 dsm-firmenich. All rights reserved."
};

// Map data keys to element IDs
const FIELD_MAP = {
  logoText: "logo-text",
  headerTagline: "header-tagline",
  heroEyebrow: "hero-eyebrow",
  heroTitle: "hero-title",
  heroDesc: "hero-desc",
  heroCta: "hero-cta",
  stat1Num: "stat1-num", stat1Label: "stat1-label",
  stat2Num: "stat2-num", stat2Label: "stat2-label",
  stat3Num: "stat3-num", stat3Label: "stat3-label",
  stat4Num: "stat4-num", stat4Label: "stat4-label",
  bizTitle: "biz-title", bizSub: "biz-sub",
  biz1Name: "biz1-name", biz1Desc: "biz1-desc",
  biz2Name: "biz2-name", biz2Desc: "biz2-desc",
  biz3Name: "biz3-name", biz3Desc: "biz3-desc",
  biz4Name: "biz4-name", biz4Desc: "biz4-desc",
  sustainEyebrow: "sustain-eyebrow", sustainTitle: "sustain-title",
  sustainDesc: "sustain-desc", sustainCta: "sustain-cta",
  sustainBadge1Title: "sustain-badge1-title", sustainBadge1Desc: "sustain-badge1-desc",
  sustainBadge2Title: "sustain-badge2-title", sustainBadge2Desc: "sustain-badge2-desc",
  sustainBadge3Title: "sustain-badge3-title", sustainBadge3Desc: "sustain-badge3-desc",
  innovEyebrow: "innov-eyebrow", innovTitle: "innov-title",
  innovDesc: "innov-desc", innovCta: "innov-cta",
  newsTitle: "news-title",
  news1Tag: "news1-tag", news1Headline: "news1-headline",
  news1Excerpt: "news1-excerpt", news1Date: "news1-date",
  news2Tag: "news2-tag", news2Headline: "news2-headline",
  news2Excerpt: "news2-excerpt", news2Date: "news2-date",
  news3Tag: "news3-tag", news3Headline: "news3-headline",
  news3Excerpt: "news3-excerpt", news3Date: "news3-date",
  cta1Title: "cta1-title", cta1Desc: "cta1-desc", cta1Btn: "cta1-btn",
  cta2Title: "cta2-title", cta2Desc: "cta2-desc", cta2Btn: "cta2-btn",
  footerLogoText: "footer-logo-text",
  footerSlogan: "footer-slogan",
  footerCopy: "footer-copy"
};
